project_id = "xzcshuoelidzdlihnwme"

[functions.subscribe-push]
verify_jwt = false

[functions.notify-push]
verify_jwt = false

[functions.profile-pin]
verify_jwt = false

[functions.process-reminders]
verify_jwt = false
